<img src="https://user-images.strikinglycdn.com/res/hrscywv4p/image/upload/c_limit,fl_lossy,h_300,w_300,f_auto,q_auto/1266110/Logo_wzxi0f.png" style="float: left; margin: 20px; height: 55px">

**Antes de morir quiero el cielo; el ciento por cierto - [C. Tangana](https://en.wikipedia.org/wiki/C._Tangana)**

# Validation

## Regressor

[SLIDES](https://docs.google.com/presentation/d/1z7DdZ4jwFo48y1FbwrkqHdzO55ZYjbVwSJ2d5tpjJKo/edit?usp=sharing)

###### Set-up

In [1]:
import numpy as np
import pandas as pd

from sklearn.model_selection import train_test_split, KFold, cross_validate
from sklearn.linear_model import LinearRegression
from sklearn.datasets import fetch_california_housing

Data extraction for this particular example

In [2]:
data = fetch_california_housing()

Features vs Target separation

In [3]:
X = pd.DataFrame(data['data'],columns=data['feature_names'])
y = pd.DataFrame(data['target'])

A bit of Exploratory Data Analisis

In [4]:
X.shape

(20640, 8)

In [5]:
X.head()

MedInc  HouseAge  AveRooms  AveBedrms  Population  AveOccup  Latitude  \
0  8.3252      41.0  6.984127   1.023810       322.0  2.555556     37.88   
1  8.3014      21.0  6.238137   0.971880      2401.0  2.109842     37.86   
2  7.2574      52.0  8.288136   1.073446       496.0  2.802260     37.85   
3  5.6431      52.0  5.817352   1.073059       558.0  2.547945     37.85   
4  3.8462      52.0  6.281853   1.081081       565.0  2.181467     37.85   

   Longitude  
0    -122.23  
1    -122.22  
2    -122.24  
3    -122.25  
4    -122.25

In [6]:
y.head()

0
0  4.526
1  3.585
2  3.521
3  3.413
4  3.422

### Train vs Test split

<img src= "Resources/train_test_split.png" style = "width: 600px;">

In [7]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=.2, random_state=42)

In [8]:
X_train.shape

(16512, 8)

In [9]:
X_test.shape

(4128, 8)

Training and validating with Train test split

In [10]:
lin_reg = LinearRegression()

In [11]:
lin_reg.fit(X_train,y_train);

In [12]:
lin_reg.score(X_train, y_train)

0.6125511913966952

In [13]:
lin_reg.score(X_test, y_test)

0.5757877060324512

### Kfold Cross-Validation

<img src= "Resources/kfold.png" style = "width: 600px;">

In [14]:
# Determining how we would like the data to be split
kf = KFold(5, random_state=888, shuffle=True)

In [15]:
kf

KFold(n_splits=5, random_state=888, shuffle=True)

In [16]:
for train_index, test_index in kf.split(X):
    print("TRAIN:", train_index, "TEST:", test_index)

TRAIN: [    0     1     2 ... 20636 20637 20639] TEST: [   21    30    36 ... 20631 20632 20638]
TRAIN: [    2     3     4 ... 20637 20638 20639] TEST: [    0     1     5 ... 20616 20624 20625]
TRAIN: [    0     1     2 ... 20636 20638 20639] TEST: [    7    22    25 ... 20634 20635 20637]
TRAIN: [    0     1     4 ... 20635 20637 20638] TEST: [    2     3     8 ... 20623 20636 20639]
TRAIN: [    0     1     2 ... 20637 20638 20639] TEST: [    4     6    15 ... 20626 20627 20629]


Training and Validating with KFolds

In [17]:
lin_reg = LinearRegression()

In [18]:
result = cross_validate(lin_reg, X, y, cv=kf,
               return_train_score=True, return_estimator=True)

In [19]:
result

{'fit_time': array([0.00954032, 0.00699329, 0.00750065, 0.00740862, 0.0068562 ]),
 'score_time': array([0.00445986, 0.00316024, 0.00605249, 0.00317788, 0.00323772]),
 'estimator': (LinearRegression(),
  LinearRegression(),
  LinearRegression(),
  LinearRegression(),
  LinearRegression()),
 'test_score': array([0.61292219, 0.59403748, 0.60012767, 0.59645999, 0.60437023]),
 'train_score': array([0.6042293 , 0.60805321, 0.6076259 , 0.60852969, 0.60452869])}

In [20]:
result['train_score']

array([0.6042293 , 0.60805321, 0.6076259 , 0.60852969, 0.60452869])

In [21]:
result['test_score']

array([0.61292219, 0.59403748, 0.60012767, 0.59645999, 0.60437023])

Comparing the mean of the splits - Train vs Test

In [22]:
np.mean(result['train_score'])

0.6065933558414665

In [23]:
np.mean(result['test_score'])

0.6015835107933769

### Train / Validation / Test split

<img src= "Resources/train_val_test.png" style = "width: 600px;">

In [24]:
X_train, X_test, y_train, y_test = train_test_split(X, y,test_size=1000, random_state=42)

In [25]:
X_train_v, X_val, y_train_v, y_val = train_test_split(X_train, y_train, test_size=1000, random_state=123)

Training and Validating with Train / Validation / Test

In [26]:
lin_reg = LinearRegression()

In [27]:
lin_reg.fit(X_train_v, y_train_v);

In [28]:
lin_reg.score(X_train_v, y_train_v)

0.6076265709233504

In [29]:
lin_reg.score(X_val, y_val)

0.5812494792349644

If we are happy with our final model we proceed to check its performance on the TEST dataset 

In [30]:
lin_reg.fit(X_train,y_train)
lin_reg.score(X_test,y_test)

0.6032561742961653

### Nested KFold

<img src= "Resources/nested_kfold.png" style = "width: 600px;">

In [31]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=.2, random_state=42)

In [32]:
kf = KFold(5, random_state=777, shuffle=True)

Training and Validating with Nested KFold

In [33]:
result = cross_validate(lin_reg, X_train, y_train, cv=kf,
               return_train_score=True, return_estimator=True)

In [34]:
result['train_score']

array([0.61333341, 0.61177594, 0.61425314, 0.60872481, 0.61512626])

In [35]:
# Checking CV validation performance
result['test_score']

array([0.60898237, 0.61509977, 0.60495645, 0.62649744, 0.60103304])

In [36]:
np.mean(result['train_score'])

0.6126427126239943

In [37]:
# Checking CV validation performance
np.mean(result['test_score'])

0.6113138138821971

If we are happy with our final model we proceed to check its performance on the TEST dataset 

In [38]:
lin_reg.fit(X_train,y_train)
lin_reg.score(X_test,y_test)

0.5757877060324512

## Classifier

[SLIDES](https://docs.google.com/presentation/d/1SFudgFyuKo9maTMhHke5GOrhNx7S-cuPAxU6O9Y1_r8/edit?usp=sharing)

### Challenge

#### Problem Understanding

The National Health Service has determined that decisive action to treat diabetes is necessary. However, diagnosing it takes hours of doctors that are in high demand.<br>

Help them to predict who is diabetic and who is not based on data that non-medical stuff can obtain so that you reduce the number of people who:
- get treated without needing it
- don't get treated when they actually needed it

#### Data Understanding

https://data.world/data-society/pima-indians-diabetes-database

In [39]:
df = pd.read_csv('Resources/pima-indians-diabetes.csv')
print(df.shape)
df.head()

(768, 9)


Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0            6      148             72             35        0  33.6   
1            1       85             66             29        0  26.6   
2            8      183             64              0        0  23.3   
3            1       89             66             23       94  28.1   
4            0      137             40             35      168  43.1   

   DiabetesPedigreeFunction  Age  Outcome  
0                     0.627   50        1  
1                     0.351   31        0  
2                     0.672   32        1  
3                     0.167   21        0  
4                     2.288   33        1

In [40]:
X = df.drop('Outcome',axis=1)
y = df['Outcome']
X.head()

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0            6      148             72             35        0  33.6   
1            1       85             66             29        0  26.6   
2            8      183             64              0        0  23.3   
3            1       89             66             23       94  28.1   
4            0      137             40             35      168  43.1   

   DiabetesPedigreeFunction  Age  
0                     0.627   50  
1                     0.351   31  
2                     0.672   32  
3                     0.167   21  
4                     2.288   33

#### Data preparation

##### Split your X data in train and test datasets
Here is the documentation: https://scikit-learn.org/stable/modules/generated/sklearn.model_selection.train_test_split.html

In [41]:
from sklearn.model_selection import train_test_split
# 
# 
# 

##### Split your train data in train and validation datasets

In [42]:
# 
# 
# 

##### Scale the 3 datasets using StandardScaler

In [43]:
from sklearn.preprocessing import StandardScaler 
# 
# 
# 

#### Modelling and Model Evaluation

##### Train a logistic regression model with NO regularisation

In [44]:
from sklearn.linear_model import LogisticRegression
# 
# 
# 

##### Measure the accuracy and ROC_AUC of your model
Here is the documentation: https://scikit-learn.org/stable/modules/model_evaluation.html#classification-metrics

In [45]:
from sklearn.metrics import accuracy_score, roc_auc_score
# 
# 
# 
# 
# 
# 

##### Train a logistic regression model with L1 regularisation

In [46]:
# 
# 
# 
# 

##### Measure the accuracy and ROC_AUC of your model


In [47]:
# 
# 
# 
# 
# 

#### Which model did you choose? Explain your reasoning

In [48]:
# 
# 
# 
# 
# 

##### Interprete your winning model

##### Extract your intercept and coefficients

In [49]:
# 
# 
# 
# 

##### Show the difference in probabilities when changing the value of one of your predictors

In [50]:
# 
# 
# 
# 
# 

##### Extract the probability of a positive for your validation samples

In [51]:
# 
# 
# 
# 

##### Extract FPR, TPR and thresholds

In [52]:
# 
# 
# 
# 

##### Plot the ROC curves for your training, validation (and, if you are done, test) datasets

In [53]:
# 
# 
# 
# 

#### Threshold selection

##### Estimate the prevalence in the environment where your model will be used

In [54]:
# 
# 
# 
# 
# 

##### Estimate the costs for each unit of your FPs, TNs, FNs and TPs
**Hint:** You don't have data for this. You will have to do some research and deep thinking<br>
**Hint 2:** think of a £ value or something else that non-technical stakeholders could relate to<br>
**Hint 3:** They are going to be approximations and that's fine. Just create a good logic.<br>

In [ ]:
FPc = 
TNc = 
FNc = 
TPc =

##### Calculate your m parameter

In [ ]:
# 
# 
# 
# 
# 

##### Calculate fm for each threshold

In [ ]:
# 
# 
# 
# 
# 

##### Select the threshold with the highest fm score

In [ ]:
# 
# 
# 
# 
# 

##### Plot the confusion matrix for your selected threshold

In [ ]:
# 
# 
# 
# 
# 

##### Calculate your alpha / power / precision / accuracy
(Don't use any library for this exercise, in real life you can though)

In [ ]:
# 
# 
# 
# 
# 

##### Explain in non-technical terms your alpha / power / precision / accuracy

In [ ]:
# 
# 
# 
# 
# 

#### Actionable problem solving recommendations

##### Write a brief paragraph telling your stakeholders something they can **DO** to be better off based on your model

In [ ]:
# 
# 
# 
# 
# 